### PR TITLE
Update Sql_faq.md

### PR DESCRIPTION
**Pull request by luo981695830**
JION should be JOIN

### CODE REVIEW

**Comment by luo981695830** [comment]
Fixes: #341
JION should be JOIN

**Review by Astralidea — APPROVED** [review]

**Review by luo981695830 — COMMENTED** [review]
test,ignore

**Review by luo981695830 — COMMENTED** [review]
fixes: #342
The case should be consistent

**Review by jaogoy — APPROVED** [review]

**Comment by jaogoy** [comment]
> Fixes: #341 JION should be JOIN

You can link to issue #341 in "Development" field.

**Pull request merged**
