### PR TITLE
[Doc] spelling of EXPLAIN

### PR DESCRIPTION
**Pull request by DanRoscigno**
change PALIN to PLAIN

### CODE REVIEW

**Comment by evelynzhaojie** [comment]
thanks

**Review by hellolilyliuyi — APPROVED** [review]

**Comment by hellolilyliuyi** [comment]
@mergify backport branch-3.1 branch-3.0 branch-2.5

**Comment by hellolilyliuyi** [comment]
@mergify backport 3.1 3.0 2.5

**Comment by hellolilyliuyi** [comment]
@mergify backport 2.4

**Pull request merged**
