### PR TITLE
Add two "show create" sql

### LINKED ISSUE #802: [New Content]: 缺少show create函数文档
### Describe the Content

缺少show create函数文档

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by femiiii**
Fixes #802 #1333 #982

### CODE REVIEW

**Review by hellolilyliuyi — APPROVED** [review]

**Comment by femiiii** [comment]
@mergify backport 2.3

**Comment by femiiii** [comment]
@mergify backport 2.2

**Comment by femiiii** [comment]
@mergify backport 2.1

**Comment by femiiii** [comment]
@mergify backport 2.0

**Comment by femiiii** [comment]
@mergify backport 1.19

**Pull request merged**
