### PR TITLE
Update SHOW DELETE.md

### PR DESCRIPTION
**Pull request by wangsimo0**

### CODE REVIEW

**Comment by wangsimo0** [comment]
@mergify backport 2.5

**Comment by wangsimo0** [comment]
@mergify backport 2.4

**Comment by wangsimo0** [comment]
@mergify backport 2.3

**Comment by wangsimo0** [comment]
@mergify backport 2.2

**Comment by wangsimo0** [comment]
@mergify backport 2.1

**Comment by wangsimo0** [comment]
@mergify backport 2.0

**Comment by wangsimo0** [comment]
@mergify backport 1.19

**Review by evelynzhaojie — APPROVED** [review]

**Pull request merged**
