### PR TITLE
[Doc] update loading intro

### PR DESCRIPTION
**Pull request by amber-create**
Signed-off-by: amber-create <yangyanping@starrocks.com>

### CODE REVIEW

**Review by evelynzhaojie — APPROVED** [review]

**Comment by amber-create** [comment]
@mergify backport 2.5

**Comment by amber-create** [comment]
@mergify backport 2.5

**Comment by amber-create** [comment]
@mergify backport 2.4

**Comment by amber-create** [comment]
@mergify backport 2.3 2.2

**Pull request merged**
