### PR TITLE
fix bug in loading from mysql

### PR DESCRIPTION
**Pull request by hellolilyliuyi**
Signed-off-by: hellolilyliuyi <hellolilyliuyi123@163.com>

### CODE REVIEW

**Review by evelynzhaojie — APPROVED** [review]

**Review by EsoragotoSpirit — APPROVED** [review]

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.5

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.4

**Comment by hellolilyliuyi** [comment]
@mergify backport branch-2.3

**Comment by hellolilyliuyi** [comment]
backport branch 2.3

**Comment by hellolilyliuyi** [comment]
backport branch 2.2

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.2

**Comment by hellolilyliuyi** [comment]
@mergify backport branch-2.3

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.3

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.3

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.4

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.3

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.3

**Pull request merged**
