### PR TITLE
add synchronize mysql into sr faq

### PR DESCRIPTION
**Pull request by hellolilyliuyi**

### CODE REVIEW

**Comment by hellolilyliuyi** [comment]
run markdownlint / markdownlint (pull_request)

**Comment by hellolilyliuyi** [comment]
run markdownlint

**Review by femiiii — APPROVED** [review]

**Comment by hellolilyliuyi** [comment]
@mergify backport branch-2.4

**Comment by hellolilyliuyi** [comment]
@mergify backport branch 2.4

**Pull request merged**
