### PR TITLE
modify examples in create routine load

### PR DESCRIPTION
**Pull request by hellolilyliuyi**

### CODE REVIEW

**Review by amber-create — APPROVED** [review]

**Comment by hellolilyliuyi** [comment]
@mergify backport 2.5

**Comment by hellolilyliuyi** [comment]
@mergify backport 2.4

**Comment by hellolilyliuyi** [comment]
@mergify backport 2.3

**Comment by hellolilyliuyi** [comment]
@mergify backport 2.2

**Comment by hellolilyliuyi** [comment]
@mergify backport 2.2

**Pull request merged**
